import type { Metadata } from "next";
import { montserrat } from "@/components/ui/fonts";
import "../styles/globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.className}  antialiased`}
      >
        <h1>sadsa</h1>
        {children}
      </body>
    </html>
  );
}
