import type { Metadata } from "next";
import { montserrat } from "@/components/ui/fonts";
import "../styles/globals.css";
import { Navbar } from "@/components/navbar/Navbar";
import { Footer } from "@/components/footer/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.className}  antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
